In [1]:
from invincible_ii_type_airship_parts import generate_gathering_list

# Generate the gathering list and save to 'gathering_list.csv'
df_gathering_list = generate_gathering_list(
    total_csv='invincible_ii_type_aftcastle_parts.csv',
    recipe_book_csv='recipe_book.csv',
    recipe_gathering_csv='recipe_gathering.csv',
    output_csv='gathering_list.csv'
)

df_gathering_list  # Display the gathering list

,Ingredient,Total Quantity,Location Info
19,Aqueous Whetstone,81.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
0,Bomb Ash,90.0,Southern Thanalan ( 22.2 / 29.9 )
15,Cedar Log,60.0,Coerthas Western Highlands ( 31.3 / 32.1 )
4,Cobalt Ore,183.0,Northern Thanalan ( 23.1 / 24.2 )
7,Coke,351.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
22,Copper Ore,24.0,Central Thanalan ( 19.0 / 26.2 )
14,Darksteel Ore,180.0,"Coerthas Central Highlands ( 27.5 / 20.0 ), Ti..."
9,Earth Cluster,9.0,NaN
8,Fire Cluster,48.0,NaN
13,Fire Crystal,288.0,NaN
3,Fire Shard,840.0,NaN
21,Gold Ore,72.0,"Eastern Thanalan ( 27.3 / 21.3 ), Timed at 10:..."
17,Holy Water,24.0,"Nowhere ( 0.0 / 0.0 ), Sold by Idyllshire Scra..."
5,Ice Shard,300.0,NaN
2,Iron Ore,258.0,"Nowhere ( 0.0 / 0.0 ), Sold by Material Supplier"
1,Iron Ore,258.0,Western Thanalan ( 27.2 / 17.4 )
12,Mythril Ore,18.0,Southern Thanalan ( 25.2 / 39.9 )
10,Mythrite Ore,72.0,Coerthas Western Highlands ( 31.2 / 12.8 )
11,Mythrite Sand,90.0,Coerthas Western Highlands ( 16.6 / 13.1 )
23,Peacock Ore,108.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
18,Raw Celestine,27.0,"Nowhere ( 0.0 / 0.0 ), Collected from Company ..."
6,Vivianite,27.0,"Nowhere ( 0.0 / 0.0 ), Collected from Company ..."
20,Wind Cluster,21.0,NaN
16,Wind Crystal,144.0,NaN

In [2]:
from invincible_ii_type_airship_parts import get_crafting_recipes

# Get the crafting recipes from total_invincible_ii_type_airship_parts.csv
df_crafting_recipes = get_crafting_recipes('invincible_ii_type_aftcastle_parts.csv')
df_crafting_recipes  # Display the crafting recipes list

              Product  Required Quantity
8           Celestine                  9
2  Cobalt Joint Plate                 60
7       Cobalt Rivets                 18
5     Darksteel Ingot                 30
3       Garlond Steel                  9
6   Holy Cedar Lumber                 12
4      Mythrite Ingot                 18
9     Rose Gold Ingot                 12
1         Steel Ingot                 30
0        Steel Rivets                 60