In [3]:
import sys
import os
sys.path.insert(0, os.path.abspath('../../'))
from workshop_projects import generate_gathering_list
utils_dir = '../../utilities/'
data_dir = 'item_data/'
df_gathering_list = generate_gathering_list(
    total_csv=os.path.join(data_dir, 'bronco_type_aftcastle_parts.csv'),
    recipe_book_csv=os.path.join(utils_dir, 'recipe_book.csv'),
    recipe_gathering_csv=os.path.join(utils_dir, 'recipe_gathering.csv'),
    output_csv=os.path.join(data_dir, 'gathering_list.csv')
)
df_gathering_list

,Ingredient,Total Quantity,Location Info
0,Bomb Ash,108.0,Southern Thanalan ( 22.2 / 29.9 )
4,Cobalt Ore,96.0,Northern Thanalan ( 23.1 / 24.2 )
8,Coke,81.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
6,Darksteel Ore,126.0,"Coerthas Central Highlands ( 27.5 / 20.0 ), Ti..."
9,Fire Cluster,9.0,NaN
7,Fire Crystal,126.0,NaN
3,Fire Shard,828.0,NaN
11,Ice Crystal,36.0,NaN
5,Ice Shard,210.0,NaN
1,Iron Ore,354.0,Western Thanalan ( 27.2 / 17.4 )
2,Iron Ore,354.0,"Nowhere ( 0.0 / 0.0 ), Sold by Material Supplier"
10,Mythril Ore,90.0,Southern Thanalan ( 25.2 / 39.9 )
12,Silver Ore,90.0,South Shroud ( 16.1 / 19.7 )
13,Wind Shard,60.0,NaN

In [4]:
import sys
import os
sys.path.insert(0, os.path.abspath('../../'))
from workshop_projects import get_crafting_recipes
data_dir = 'item_data/'
df_crafting_recipes = get_crafting_recipes(os.path.join(data_dir, 'bronco_type_aftcastle_parts.csv'))
df_crafting_recipes

              Product  Required Quantity
1        Cobalt Ingot                 24
3  Cobalt Joint Plate                 24
4     Darksteel Ingot                  9
8     Darksteel Plate                 12
5         Iron Rivets                 30
7      Mythril Rivets                 30
9        Silver Ingot                 30
2         Steel Ingot                 54
6   Steel Joint Plate                 30
0        Steel Rivets                 24