In [2]:
import sys
import os
sys.path.insert(0, os.path.abspath('../../'))
from workshop_projects import generate_gathering_list
utils_dir = '../../utilities/'
data_dir = 'item_data/'
df_gathering_list = generate_gathering_list(
    total_csv=os.path.join(data_dir, 'invincible_type_aftcastle_parts.csv'),
    recipe_book_csv=os.path.join(utils_dir, 'recipe_book.csv'),
    recipe_gathering_csv=os.path.join(utils_dir, 'recipe_gathering.csv'),
    output_csv=os.path.join(data_dir, 'gathering_list.csv')
)
df_gathering_list

,Ingredient,Total Quantity,Location Info
0,Bomb Ash,108.0,Southern Thanalan ( 22.2 / 29.9 )
6,Cobalt Ore,195.0,Northern Thanalan ( 23.1 / 24.2 )
5,Coke,162.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
10,Darksteel Ore,54.0,"Coerthas Central Highlands ( 27.5 / 20.0 ), Ti..."
8,Earth Cluster,9.0,NaN
7,Fire Cluster,18.0,NaN
11,Fire Crystal,54.0,NaN
3,Fire Shard,948.0,NaN
15,Ice Cluster,9.0,NaN
9,Ice Shard,210.0,NaN
2,Iron Ore,300.0,"Nowhere ( 0.0 / 0.0 ), Sold by Material Supplier"
1,Iron Ore,300.0,Western Thanalan ( 27.2 / 17.4 )
16,Mythril Ore,90.0,Southern Thanalan ( 25.2 / 39.9 )
12,Petrified Log,9.0,"Nowhere ( 0.0 / 0.0 ), Sold for 1500 GC Seals"
13,Scarlet Sap,9.0,"North Shroud ( 17.7 / 27.7 ), Timed at 1:00am"
17,Silver Ore,90.0,South Shroud ( 16.1 / 19.7 )
4,Vivianite,27.0,"Nowhere ( 0.0 / 0.0 ), Collected from Company ..."
14,Wind Cluster,18.0,NaN
18,Wind Shard,60.0,NaN

In [1]:
import sys
import os
sys.path.insert(0, os.path.abspath('../../'))
from workshop_projects import get_crafting_recipes
data_dir = 'item_data/'
df_crafting_recipes = get_crafting_recipes(os.path.join(data_dir, 'invincible_type_aftcastle_parts.csv'))
df_crafting_recipes

              Product  Required Quantity
7      Ancient Lumber                  9
6        Cobalt Ingot                 60
3  Cobalt Joint Plate                 24
4     Darksteel Ingot                  9
1       Garlond Steel                  9
8      Mythril Rivets                 30
9        Silver Ingot                 30
2         Steel Ingot                 54
5   Steel Joint Plate                 30
0        Steel Rivets                 24