In [1]:
from tatanora_type_airship_parts import generate_gathering_list

# Generate the gathering list and save to 'gathering_list.csv'
df_gathering_list = generate_gathering_list(
    total_csv='tatanora_type_forecastle_parts.csv',
    recipe_book_csv='recipe_book.csv',
    recipe_gathering_csv='recipe_gathering.csv',
    output_csv='gathering_list.csv'
)

df_gathering_list  # Display the gathering list

,Ingredient,Total Quantity,Location Info
2,Adamantite Ore,105.0,"Azys Lla ( 23.2 / 5.8 ), Timed at 12AM/PM ET"
24,Aqueous Whetstone,81.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
17,Cassia Log,54.0,"Nowhere ( 0.0 / 0.0 ), Collected from Company ..."
16,Cassia Log,54.0,"Nowhere ( 0.0 / 0.0 ), Collected from Company ..."
13,Cloud Mica,72.0,The Churning Mists ( 27.6 / 19.2 )
4,Cobalt Ore,147.0,Northern Thanalan ( 23.1 / 24.2 )
9,Coke,243.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
3,Darksteel Ore,273.0,"Coerthas Central Highlands ( 27.5 / 20.0 ), Ti..."
11,Earth Cluster,9.0,NaN
10,Fire Cluster,36.0,NaN
12,Fire Crystal,666.0,NaN
1,Fire Shard,540.0,NaN
15,Grenade Ash,18.0,"Nowhere ( 0.0 / 0.0 ), Purchased from Z'ranmai..."
18,Hardened Sap,162.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
20,Ice Cluster,18.0,NaN
7,Ice Shard,300.0,NaN
6,Iron Ore,78.0,"Nowhere ( 0.0 / 0.0 ), Sold by Material Supplier"
5,Iron Ore,78.0,Western Thanalan ( 27.2 / 17.4 )
0,Mythril Ore,108.0,Southern Thanalan ( 25.2 / 39.9 )
21,Mythrite Ore,72.0,Coerthas Western Highlands ( 31.2 / 12.8 )
22,Mythrite Sand,90.0,Coerthas Western Highlands ( 16.6 / 13.1 )
23,Raw Celestine,27.0,"Nowhere ( 0.0 / 0.0 ), Collected from Company ..."
14,Titanium Ore,90.0,The Dravanian Forelands ( 30.3 / 15.1 )
8,Vivianite,27.0,"Nowhere ( 0.0 / 0.0 ), Collected from Company ..."
19,Wind Cluster,45.0,NaN

In [2]:
from tatanora_type_airship_parts import get_crafting_recipes

# Get the crafting recipes from total_tatanora_type_airship_parts.csv
df_crafting_recipes = get_crafting_recipes('tatanora_type_forecastle_parts.csv')
df_crafting_recipes  # Display the crafting recipes list

              Product  Required Quantity
1   Adamantite Nugget                 21
7       Cassia Lumber                 18
9           Celestine                  9
2  Cobalt Joint Plate                 60
6     Darksteel Ingot                 18
4    Darksteel Rivets                 48
3       Garlond Steel                  9
0      Mythril Rivets                 30
8      Mythrite Ingot                 18
5      Titanium Ingot                 18