In [1]:
import sys
import os
sys.path.insert(0, os.path.abspath('../../'))
from workshop_projects import generate_gathering_list
utils_dir = '../../utilities/'
data_dir = 'item_data/'
df_gathering_list = generate_gathering_list(
    total_csv=os.path.join(data_dir, 'unkiu_class_pressure_hull_parts.csv'),
    recipe_book_csv=os.path.join(utils_dir, 'recipe_book.csv'),
    recipe_gathering_csv=os.path.join(utils_dir, 'recipe_gathering.csv'),
    output_csv=os.path.join(data_dir, 'gathering_list.csv')
)
df_gathering_list

,Ingredient,Total Quantity,Location Info
20,Black Alumen,24.0,South Shroud ( 28.7 / 22.8 )
4,Bomb Ash,72.0,Southern Thanalan ( 22.2 / 29.9 )
10,Cobalt Ore,75.0,Northern Thanalan ( 23.1 / 24.2 )
9,Coke,81.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
12,Earth Cluster,9.0,NaN
21,Earth Crystal,24.0,NaN
18,Electrum Ore,96.0,Upper La Noscea ( 30.4 / 25.4 )
11,Fire Cluster,9.0,NaN
7,Fire Shard,384.0,NaN
26,Flax,36.0,South Shroud ( 17.6 / 28.6 )
29,Gelato Flesh,27.0,"Coerthas Western Highlands ( 9.4 / 18.8 ), Dr..."
16,Ice Cluster,24.0,NaN
17,Ice Shard,72.0,NaN
5,Iron Ore,240.0,Western Thanalan ( 27.2 / 17.4 )
6,Iron Ore,240.0,"Nowhere ( 0.0 / 0.0 ), Sold by Material Supplier"
24,Lightning Cluster,9.0,NaN
0,Oak Log,72.0,South Shroud ( 16.6 / 30.2 )
13,Petrified Log,24.0,"Nowhere ( 0.0 / 0.0 ), Sold for 1500 GC Seals"
23,Potash,81.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
30,Pudding Flesh,18.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
25,Raw Amber,36.0,Eastern Thanalan ( 12.7 / 19.1 )
22,Red Moko Grass,27.0,"Nowhere ( 0.0 / 0.0 ), Collected from Company ..."
14,Scarlet Sap,24.0,"North Shroud ( 17.7 / 27.7 ), Timed at 1:00am"
2,Spruce Log,72.0,"Coerthas Central Highlands ( 29.5 / 13.1 ), Ti..."
28,Terebinth,18.0,"Nowhere ( 0.0 / 0.0 ), Sold by Main City NPCs"
19,Uraeus Skin,24.0,"Nowhere ( 0.0 / 0.0 ), Found in The Wanderer's..."
8,Vivianite,27.0,"Nowhere ( 0.0 / 0.0 ), Collected from Company ..."
31,Water Crystal,27.0,NaN
27,Water Shard,144.0,NaN
15,Wind Cluster,57.0,NaN
3,Wind Crystal,72.0,NaN
1,Wind Shard,192.0,NaN

In [2]:
import sys
import os
sys.path.insert(0, os.path.abspath('../../'))
from workshop_projects import get_crafting_recipes
data_dir = 'item_data/'
df_crafting_recipes = get_crafting_recipes(os.path.join(data_dir, 'unkiu_class_pressure_hull_parts.csv'))
df_crafting_recipes

            Product  Required Quantity
4    Ancient Lumber                 24
8      Cobalt Ingot                 24
7    Electrum Ingot                 24
10  Farreach Canvas                  9
3     Garlond Steel                  9
5       Iron Rivets                 24
0        Oak Lumber                 24
1     Spruce Lumber                 24
2       Steel Nails                 24
6       Steel Plate                 24
9    Uraeus Leather                 24
11          Varnish                 18
12        Void Glue                  9