In [1]:
import sys
import os
sys.path.insert(0, os.path.abspath('../../'))
from workshop_projects import generate_gathering_list
utils_dir = '../../utilities/'
data_dir = 'item_data/'
df_gathering_list = generate_gathering_list(
    total_csv=os.path.join(data_dir, 'unkiu_class_stern_parts.csv'),
    recipe_book_csv=os.path.join(utils_dir, 'recipe_book.csv'),
    recipe_gathering_csv=os.path.join(utils_dir, 'recipe_gathering.csv'),
    output_csv=os.path.join(data_dir, 'gathering_list.csv')
)
df_gathering_list

,Ingredient,Total Quantity,Location Info
0,Bomb Ash,48.0,Southern Thanalan ( 22.2 / 29.9 )
4,Cobalt Ore,153.0,Northern Thanalan ( 23.1 / 24.2 )
6,Coke,162.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
15,Darksteel Ore,162.0,"Coerthas Central Highlands ( 27.5 / 20.0 ), Ti..."
8,Earth Cluster,27.0,NaN
20,Effervescent Water,30.0,South Shroud ( 16.0 / 19.7 )
17,Ferberite,18.0,"Northern Thanalan ( 17.3 / 19.9 ), Timed at 3:..."
7,Fire Cluster,54.0,NaN
13,Fire Crystal,270.0,NaN
3,Fire Shard,528.0,NaN
18,Ice Crystal,54.0,NaN
14,Ice Shard,150.0,NaN
2,Iron Ore,150.0,"Nowhere ( 0.0 / 0.0 ), Sold by Material Supplier"
1,Iron Ore,150.0,Western Thanalan ( 27.2 / 17.4 )
9,Mythril Rivets,60.0,NaN
12,Mythril Ore,108.0,Southern Thanalan ( 25.2 / 39.9 )
10,Mythrite Ore,72.0,Coerthas Western Highlands ( 31.2 / 12.8 )
11,Mythrite Sand,90.0,Coerthas Western Highlands ( 16.6 / 13.1 )
21,Rock Salt,30.0,Central Thanalan ( 14.5 / 22.7 )
16,Scheelite,18.0,"Nowhere ( 0.0 / 0.0 ), Sold for 1500 GC Seals"
19,Silex,30.0,Southern Thanalan ( 22.4 / 29.7 )
5,Vivianite,27.0,"Nowhere ( 0.0 / 0.0 ), Collected from Company ..."
22,Water Shard,150.0,NaN

In [2]:
import sys
import os
sys.path.insert(0, os.path.abspath('../../'))
from workshop_projects import get_crafting_recipes
data_dir = 'item_data/'
df_crafting_recipes = get_crafting_recipes(os.path.join(data_dir, 'unkiu_class_stern_parts.csv'))
df_crafting_recipes

               Product  Required Quantity
11    Clear Glass Lens                 30
1         Cobalt Ingot                 24
6   Cobalt Joint Plate                 30
7      Darksteel Ingot                  9
9      Darksteel Plate                 18
3        Garlond Steel                  9
4      Mythril  Rivets                 60
10       Mythril Ingot                 30
5       Mythrite Ingot                 18
2          Steel Ingot                 24
0         Steel Rivets                 24
8        Wolfram Ingot                 18