In [1]:
import sys
import os
sys.path.insert(0, os.path.abspath('../../'))
from workshop_projects import generate_gathering_list
utils_dir = '../../utilities/'
data_dir = 'item_data/'
df_gathering_list = generate_gathering_list(
    total_csv=os.path.join(data_dir, 'whale_class_bridge_parts.csv'),
    recipe_book_csv=os.path.join(utils_dir, 'recipe_book.csv'),
    recipe_gathering_csv=os.path.join(utils_dir, 'recipe_gathering.csv'),
    output_csv=os.path.join(data_dir, 'gathering_list.csv')
)
df_gathering_list

,Ingredient,Total Quantity,Location Info
16,Aqueous Whetstone,81.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
0,Bomb Ash,90.0,Southern Thanalan ( 22.2 / 29.9 )
22,Cedar Log,60.0,Coerthas Western Highlands ( 31.3 / 32.1 )
4,Cobalt Ore,183.0,Northern Thanalan ( 23.1 / 24.2 )
7,Coke,189.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
19,Copper Ore,24.0,Central Thanalan ( 19.0 / 26.2 )
10,Darksteel Ore,72.0,"Coerthas Central Highlands ( 27.5 / 20.0 ), Ti..."
9,Earth Cluster,9.0,NaN
8,Fire Cluster,30.0,NaN
11,Fire Crystal,180.0,NaN
3,Fire Shard,840.0,NaN
18,Gold Ore,72.0,"Eastern Thanalan ( 27.3 / 21.3 ), Timed at 10:..."
23,Holy Water,24.0,"Nowhere ( 0.0 / 0.0 ), Sold by Idyllshire Scra..."
5,Ice Shard,300.0,NaN
2,Iron Ore,258.0,"Nowhere ( 0.0 / 0.0 ), Sold by Material Supplier"
1,Iron Ore,258.0,Western Thanalan ( 27.2 / 17.4 )
14,Mythril Ore,18.0,Southern Thanalan ( 25.2 / 39.9 )
12,Mythrite Ore,72.0,Coerthas Western Highlands ( 31.2 / 12.8 )
13,Mythrite Sand,90.0,Coerthas Western Highlands ( 16.6 / 13.1 )
21,Peacock Ore,108.0,"Nowhere ( 0.0 / 0.0 ), Sold for 200 GC Seals"
15,Raw Celestine,27.0,"Nowhere ( 0.0 / 0.0 ), Collected from Company ..."
6,Vivianite,27.0,"Nowhere ( 0.0 / 0.0 ), Collected from Company ..."
17,Wind Cluster,21.0,NaN
20,Wind Crystal,144.0,NaN

In [2]:
import sys
import os
sys.path.insert(0, os.path.abspath('../../'))
from workshop_projects import get_crafting_recipes
data_dir = 'item_data/'
df_crafting_recipes = get_crafting_recipes(os.path.join(data_dir, 'whale_class_bridge_parts.csv'))
df_crafting_recipes

              Product  Required Quantity
7           Celestine                  9
1  Cobalt Joint Plate                 60
6       Cobalt Rivets                 18
4     Darksteel Ingot                 12
3       Garlond Steel                  9
9   Holy Cedar Lumber                 12
5      Mythrite Ingot                 18
8     Rose Gold Ingot                 12
2         Steel Ingot                 30
0        Steel Rivets                 60